#Minimum lapis cost when using enchantment conversion table, when set to 0, emerald will be banned on the table
# Default: 36
# Range: 0 ~ 64
minimumEmeraldCost = 36
#Minimum lapis block cost when using enchantment conversion table, when set to 0, emerald block will be banned on the table
# Default: 4
# Range: 0 ~ 64
minimumEmeraldBlockCost = 4
#Ignore enchantment level limit when using enchantment conversion table
ignoreEnchantmentLevelLimit = true
#if set to true, enchantment conversion table will use emerald to exchange max level book
#if set to false, enchantment conversion table will use emerald to exchange 1-level book
convert_max_level_book = true
