#The new default stack size for items. Vanilla default stack size is 64. Default is 1000.
# Default: 1000
# Range: 1 ~ 1073741823
defaultStackSize = 1000
#Whether items with small stack sizes (ex: ender pearls) have a new stack size proportional to the new default stack size value. Setting this value to false will cause all items to have the same stack size. Default is true.
respectSmallStackSizes = true
#The minimum default stack size for any stack size adjustment to occur (ex: if this is set to 17 then ender pearls will keep their usual maximum stack size of 16).
# Default: 1
# Range: > 0
minimumDefaultStackSizeThreshold = 1
